
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/tiwonge/Documents/School/IPP/build/assets/frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1008x701")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 701,
    width = 1008,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    5.0,
    1008.0,
    711.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    351.0,
    13.0,
    anchor="nw",
    text="ABOUT THE DASHBOARD",
    fill="#151617",
    font=("MontserratRoman Bold", 20 * -1)
)

canvas.create_text(
    138.0,
    117.0,
    anchor="nw",
    text="This is a Uclid5 Graphic User Interface (GUI). It has two main functionalities :\n\nYou can run code directly on the Gui by clicking ‘Run Code’\nYou can upload a file\n",
    fill="#6F6C6C",
    font=("MontserratRoman Bold", 16 * -1)
)

canvas.create_text(
    312.0,
    661.0,
    anchor="nw",
    text="Copyright-University of edinburgh Project",
    fill="#428EA6",
    font=("MontserratRoman Bold", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
