
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/tiwonge/Documents/School/IPP/build/assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("2095x2000")
window.configure(bg = "#D9D9D9")


canvas = Canvas(
    window,
    bg = "#D9D9D9",
    height = 2000,
    width = 2095,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    769.0,
    67.0,
    anchor="nw",
    text="WRITE CODE",
    fill="#0F4A63",
    font=("MontserratRoman Bold", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=247.0,
    y=282.0,
    width=171.0,
    height=76.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1668.0,
    y=282.0,
    width=154.7491455078125,
    height=76.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1044.5,
    1113.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=120.0,
    y=369.0,
    width=1849.0,
    height=1487.0
)

canvas.create_text(
    77.0,
    124.0,
    anchor="nw",
    text="Go Back",
    fill="#0F4A63",
    font=("MontserratRoman Bold", 20 * -1)
)

canvas.create_text(
    692.0,
    1949.0,
    anchor="nw",
    text="Copyright-University of edinburgh Project",
    fill="#428EA6",
    font=("MontserratRoman Bold", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
